# .streamlit/secrets.toml

[usuarios]
Jose = { password = "220120", nombre = "Jose Blanco", rol = "master" }

[gcp_service_account]
type = "service_account"
project_id = "tu-proyecto-id"
private_key_id = "tu-private-key-id"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3V9rXp9uY
...aquí pegas todas las líneas que componen tu bloque real...
...sin añadir "\n" manuales, solo saltando de línea normal...
-----END PRIVATE KEY-----'''
client_email = "tu-cuenta-de-servicio@...iam.gserviceaccount.com"
client_id = "123456789"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."